# @package _global_
# Continuous Single Room Environment Configuration

env:
  name: "ContinuousSingleRoom-v0"
  room_size: 5.0
  max_steps: 200
  render_mode: rgb_array
  show_coordinates: false
  
  # Continuous movement parameters
  move_delta: 0.3
  goal_threshold: 0.4
  wall_thickness: 0.3
  agent_radius: 0.15
  
  num_actions: 4  # 4 cardinal directions + ( 4 diagonal directions if n action = 8)
  
  # Reward parameters
  dense_reward: false
  wall_penalty: 0.0
  
  # Goal position (optional, null for random at each episode)
  goal_position: null
  
  # Start position (optional, null for random at each episode)
  start_position:  [0.8, 0.8] 
  
  # Rendering
  render_resolution: 512
