# @package _global_
# Four Rooms Environment Configuration

env:
  name: "MultipleRooms-v0"
  num_rooms: 10
  room_size: 3
  corridor_height: 1
  connector_length: 1
  max_steps: 500
  render_mode: rgb_array
  show_coordinates: false

  
  # Goal position (optional, null for random at each episode)
  goal_position: [25,4]  # Can be [x, y] or null for random
  
  # Start position (optional, null for random at each episode)
  start_position:  [0, 0]  # Can be [x, y] or null for random
